version: "3.1"
services:
  app:
    env_file:
     - .env
    container_name: push-deploy
    image: push-deploy:latest
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - "./:/opt/push-deploy"

