---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: push-deploy
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-list
  namespace: default
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments"]
  verbs: ["list", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployments-list
subjects:
- kind: ServiceAccount
  name: push-deploy
  namespace: default
roleRef:
  kind: Role
  name: deployments-list
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-deploy
  template:
    metadata:
      labels:
        app: push-deploy
    spec:
      serviceAccountName: push-deploy
      containers:
      - image: push-deploy:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["push-deploy.py"]
        name: push-deploy
        resources:
          requests:
            memory: "96Mi"
            cpu: "50m"
          limits:
            memory: "256Mi" 
            cpu: "250m"
        env:
          - name: PD_NAMESPACE
            value: default
          - name: PD_DEPLOYMENT
            value: "nginx"
      imagePullSecrets:
        - name: k8s-reg-key
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
